---
title: "DH Project 1: Voyant"
author: "Group Members: Nishtha Das, Shreya Khobragade, Simran Dhiman"
date: "Date: 19/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Research Hypothesis
An exploration of the ways in which Jane Austen and Charles Dickens criticise marriage in their novels. 

### Corpus Description
We conducted a comparative study of Jane Austen and Charles Dickens’ novels. They were both contemporaries in the late 18th/early 19th century (and incredibly influential for the years to come), but the worlds they wrote about were disparate. The characters in Austen’s middle to upper-class society functioned very differently from the ones in Dickens’ slums and orphanages. Our interests lay in finding commonalities in their work as well as in the ideologies that underscored it, and we found our focus in their treatment of marriage. Both the authors deviate from the idea that marriage has to be central to one’s life, especially if one is a woman. They subtly, if not openly, criticise practices surrounding marriage in their respective social contexts. We patterned our corpus by including the year of publication in the title of the texts so they would be arranged temporally.

### Summary Paragraph
Austen’s novels kept getting marginally longer in her early years, until *Persuasion* (1818), where the length took a sharp dip (approximately 74,000 words). Another sharp dip was noticed in *Lady Susan* (1871), where the length was reduced further by 50,000 words. However, the novels that are lowest in length have the highest vocabulary densities: perhaps she developed a more concise style of writing as her career progressed, and switched out lengthy descriptions for a few unique words. 

Dickens’ body of work was more difficult to find patterns in. But all his available works were written in the time period between *Persuasion* and *Lady Susan* - Austen’s last two available novels. Like Austen, his last novel was lowest in length and highest in vocabulary density. However, his longest work (*Dombey and Son*) is more than double the length of Austen’s longest (*Emma*). This means we have a much, much larger sample of Dickens to work with: there are 15 novels as compared to Austen’s 7, and most of them span over longer lengths. We have tried to be mindful of this while doing our analysis as well.

### Tool 1: Frequency Comparison
A quick look at the list of terms reveals that “Mr” is most frequently used for both authors. But the men in Austen largely exist within the locus of marriage, while Dickens’ male characters exist in many spheres outside it. Therefore, the usage of the term “Mr” means different things for both corpora: one is high on contexts of marriage, while the other simply has more male characters (or more frequently mentioned male characters). This is further corroborated by the fact that the second most frequent word in Austen’s work is “Mrs”, while for Dickens, another title (“Sir”) appears only at number 4. Dickens did have more diverse subjects than romance and marriage, including industrialisation and poverty. “Mr” and “sir” could then contain references to authority figures at workplaces, schools, and the like. 

On the other hand, while Austen is famous for her romances, the women in her world often married for financial security, with little regard for their actual feelings. Many of them existed in a space of aspiration between the middle and upper class, and they used marriage as a tool for social mobility. To be able to land a rich man, women were doubly restricted by standards of femininity as well as of high society. Thus, our first question became: how many of Austen’s characters married for riches, and how many for love?

We ran two word clusters: love | romance | courtship | affection | marriage, and estate | riches | secure | money | marriage. As the graph indicates, the love cluster is always more frequent than the money cluster. The gap almost closes with *Persuasion*, and widens again with *Lady Susan*, which has the highest occurrences of both clusters (despite being the shortest novel!). 

<iframe style='width: 477px; height: 360px;' src='https://voyant-tools.org/tool/Trends/?query=estate%7Criches%7Csecure%7Cmoney%7Cmarriage*&query=love%7Cromance%7Ccourtship%7Caffection%7Cmarriage*&corpus=abb97de3988ddb2978277184f906c493' data-external = '1'></iframe>

For Dickens’ corpus, however, we had to change our search area. Since his marriage and class dynamics are a) so different from Austen, and b) varied across his books, we simply inquired into the number of unhappy marriages in his work. Having been a divorcee himself, he was a strong advocate for divorce. The clusters we entered were divorce|infidelity|separation, and “happy marriage”~2|fidelity|”domestic bliss”~4. Here, the divorce cluster appears more frequently in all his books, except for a few of his later ones. Part of this could be attributed to the specificity of the other cluster, but simply searching for terms like “marriage” would not have helped either, since we were searching for a specific *kind* of marriage. 

<iframe style='width: 477px; height: 360px;' src='https://voyant-tools.org/tool/Trends/?query=%E2%80%9Chappy%20marriage%E2%80%9D~2%7Cfidelity%7C%E2%80%9Ddomestic%20bliss%E2%80%9D~4*&query=divorce%7Cinfidelity%7Cseparation*&corpus=7fb0f588e55bb9c59b1e56fa8327178f' data-external = '1'></iframe>

What is interesting about these results is not where these terms appear most, rather, it is where they appear least. *Hard Times*, Dickens’ 1854 novel, describes marital separation at length. The novel was written soon after the House of Lords introduced a divorce bill, and it openly criticises the inaccessibility of divorce to the poor that was also mirrored in the bill. However, *Hard Times* is the only novel in the whole corpus where none of the words from the divorce cluster are found. Similarly, *Emma* is a critique of utilitarian marriages, depicting characters that marry for money as less moral and downright antagonistic; but it is where money-related terms are least frequent (although they still appear). 

The simplest explanation for this is avoidance of controversy, considering the times they lived in, and both authors were indeed relatively uncontroversial. Perhaps there are other terms worth exploring to make connections: for example, *Emma* scores very high on terms like “friend” and “friendship” as compared to Austen’s other works, and a new study could find out if she celebrates platonic relationships as an alternative to marriage being the centre of women’s lives. In any case, these findings not only speak to the limitations of our approach but also open up possibilities for other questions about language and deriving meaning from linguistic data.

### Tool 2: Collocation/Correlation
We then used the collocation tool to see which words occurred next to each other the most. The words that were higher up in the trends list were used so that we can restrict our analysis to the words with higher frequencies in the texts of both Charles Dickens and Jane Austen. Even though the collocation tool does not give us a very clear indication of the relationship between the words that tend to appear together, it can be useful in getting a general sense of the ideas and patterns that can be found across the texts. 

For instance, the collocates for the word “Mr” in Dickens novels include words like “Pickwick”, “said”, and “sir”; whereas the collocates for the word “Mrs” include words like “Mr”, “said”,”nickleby” and “gamp”. While this does not tell us much about how Dickens looked at marriage, we can see that the word “Mr” is used alongside the word ”Mrs” and not the other way round, perhaps involving the world of marriage more in the women's sphere of existence as compared to the men.  

Now if we were to compare the collocates of the words “Mr” and “Mrs” for Jane Austen's novels, we find that “Mr” mainly appears alongside proper nouns such as “Darcy”, “Elton”, “Crawford”, “Weston”; and “Mrs” also collocates with proper nouns (mostly male names) , namely, “weston”, “norris”, “jennings” and “mr”. This pattern is similar in both Dickens and Austen's works.

The correlation tool allowed us to see which words had a negative or positive correlation with other words; that is to say to navigate the increase or decrease of the frequencies of certain words as compared to others. In this paper, for the sake of minimizing the risk of being overwhelmed by multiple possible links between words, we have limited the search results to 5 words. 

For Charles Dickens novels, the frequencies of words like “Danger”, “Crummles”, “Summer”, “Confusion”, and “Talked” increase with the increase of the word “Mr”; whereas words like “Wurth” (worth), “Writer’s”, “Wrinkling”, “yit”, and “wreaths” are positively correlated with “Mrs”. None of these words seem like anything that can be used in a romantic setting or can indicate anything of the character’s relationship with marriage itself. 

<iframe style='width: 1440px; height: 669px;' src='https://voyant-tools.org/tool/Correlations/?view=Correlations&query=mr&minInDocumentsCountRatio=5&corpus=d89f66f27923846f1b63a8af3e46d456' data-external = '1'></iframe>

<iframe style='width: 1440px; height: 669px;' src='https://voyant-tools.org/tool/Correlations/?view=Correlations&query=mrs*&minInDocumentsCountRatio=5&corpus=d89f66f27923846f1b63a8af3e46d456' data-external = '1'></iframe>

An interesting pattern emerges within Jane Austen’s novels where the word “worthless” and “wounding” are strongly and positively correlated with both the words “Mr'' and “Mrs”, giving us a slightly more clear view of Austen’s stance on marriage, i.e, by attaching the ideas of worth and worthlessness, marriage is seen as a form of a transaction. This in some ways makes the idea of there being a vast display of emotions within her writing, in contrast to the social construct of attaching worth to a marriage, makes her idea of marriage more complicated. 

<iframe style='width: 1440px; height: 669px;' src='https://voyant-tools.org/tool/Correlations/?view=Correlations&query=mr*&minInDocumentsCountRatio=5&corpus=9bff29f50791ba5a386edf2a8c2b32b2' data-external = '1'></iframe>

<iframe style='width: 1440px; height: 669px;' src='https://voyant-tools.org/tool/Correlations/?view=Correlations&query=mrs*&minInDocumentsCountRatio=5&corpus=9bff29f50791ba5a386edf2a8c2b32b2' data-external = '1'></iframe>

### Tool 3: Context
The context tool locates and presents all the contexts (sentences) a chosen keyword appears in. It splits each sentence into a left column preceding the keyword and a right column succeeding it. This tool is used to closely study terms in various contexts. It also eliminates misconceptions because context can help explain the intended meaning of words that otherwise might be lost in definitions. For example, intercourse in Jane Austen’s novels refers to communication and not sexual intercourse. Even without reading any novels from the corpora, this tool helped form a foundational understanding of the plots and unveiled phrases/words that the other two tools might not have caught.

Since our hypothesis dealt with the authors’ treatment of marriage, we used the context tool to gather the general plot points in which it appears. So, we ran our analysis with “marriage*” to look at all of its variations. Unsurprisingly, this resulted in many occurrences: 237 for Austen and 381 for Dickens. To keep our analysis distant and not overwhelming, we stuck with the default context width of 5 words on either side of the term. While a narrow context width provided some abstraction, we noticed that a brief expansion of the contexts was repeatedly required to avoid misconceptions. For example, “tolerably happy” and “sincere affection” in row 9 would intuitively suggest a neutral/positive connotation. Yet, upon expansion, we see that the complete phrase is: “he had not even the chance to be tolerably happy in marriage”, which is evidently negative. To compile the relevant comments on marriage, we created a text-wise table with ‘Year’, ‘Text’ and ‘Term/Phrases(s)’ columns. The table majorly tracked additional information arising from expansions.

Using this, we made some inferences about the Jane Austen corpus. *Sense and Sensibility* (1811) kicks off a pattern of associating marriage with unhappiness, “commercial exchange” and convenience. *Pride and Prejudice* (1813) possibly portrays the repercussions of these associations by introducing elopement and living together before marriage. This marks an upward slope towards the antithesis of matrimony: divorce, which features in *Mansfield Park* (1814). Accordingly, this novel stresses marriage for love over convenience. In *Emma* (1815), representations of female agency in matrimonial decisions continue, in either choosing who to marry or not to marry at all. However, occurrences of marriage decrease in *Northanger Abbey* (1818), with only 12 available contexts of which only a few are critiques. This probably cannot be attributed to the length of the text because even her shortest text has more occurrences of the concept. Interestingly, this was her first finished novel (1803) but was published posthumously. It is possible that this theme was not a personal/literary priority for Austen when she first transitioned from juvenile works to mature novels. Her relatively neutral commentary could also be due to the novel’s satirical style. The last two novels, *Persuasion* (1818) and *Lady Susan* (1871) sustain Austen’s leaning towards marriage for consensual happiness rather than financial gain. 

<iframe style='width: 1440px; height: 669px;' src='https://voyant-tools.org/tool/Contexts/?view=Contexts&query=marriage*&docId=b44ef83e5a840f3fd1b307cc0fd35630&docId=457ade46d2f9f6d5e7ca7d5bc8ad09c1&docId=d6f8c12fc9920fd97bb639737d1fcb70&docId=c2f4627dab4413c7e58be3553750f95b&docId=e715834768eb617956394f85df69b41b&docId=75bb0d63f2ecfb7fdaaf8dae3578d664&docId=b7cc80a419d790a0ca01a04aa700647c&expand=65&corpus=abb97de3988ddb2978277184f906c493' data-external = '1'></iframe>

We used the same methodology and keyword to analyse the Charles Dickens corpus. Straight off the bat, we can notice a stark contrast between the approach of both authors. In *The Pickwick Papers* (1836), he states that breaches in marital contracts occur frequently and result in payouts. This legal context to matrimony is rarely present in the Austen corpus but makes a recurring appearance with Dickens. For example, *Barnaby Rudge* portrays marriage as a “civil contract”. In *Nicholas Nickleby* (1838), he briefly introduces elopement and passion, much like in *Pride and Prejudice*. From this point onwards, variations of the terms “forced” and “unequal” appear frequently in the contexts. *The Old Curiosity Shop* (1840), *Barnaby Rudge* (1841), *Martin Chuzzlewit* (1843) all depict attempts at forcing marriage upon parties. Even though Austen also touches upon non-compliance, she uses the term “force” only once in the same context. *Dombey and Son* (1846), the longest text, has 71 occurrences which is the highest count amongst the corpus. Here, similar to *Emma*, there is a discourse on the benefits of remaining unmarried. It also features a couple who acknowledge their unhappiness but decide to endure it. As a proclaimed advocate for divorce, it is intriguing that Dickens sticks to this route of forbearance. This is perhaps representative of the treatment of his own marriage, considering that he separated from his wife a few years later in 1858.

<iframe style='width: 1440px; height: 669px;' src='https://voyant-tools.org/tool/Contexts/?view=Contexts&query=marriage*&docId=f9713774de23127a4f348f3e929ab8a6&docId=8b241cd8fd5792dad5d046c9c5c4f379&docId=9066d26c80076f03c5c0832d82c2a8f5&docId=5bb3d0f53f4f18e063c9d035e8912d73&docId=5da7f9c6ffde82e5eb949efc88ffaadf&docId=f77ca886b4eae6fd3efd36f45f461f1e&docId=80ba90b94c9200744cbb67ab9a0b0192&docId=7408cffd29097ebca23aca9dd3a755ce&docId=f7f6ee943bd1c9a1d588c82cba834d3f&docId=ae64feaf750361e12183e36852a2a8ad&docId=dcf5732e5c2095ef87aff519b729ced9&docId=4f6306395433fad149b6bbe2b0515147&docId=72e89313737dff29d1ca94322029d1be&docId=ea1c778e65bc8e6921e39ae440989ef1&docId=f0d0a40a8460e858d34ebc0c8ff3e56c&corpus=7fb0f588e55bb9c59b1e56fa8327178f' data-external = '1'></iframe>

Dickens’s commentary on marriage in his remaining novels from 1849-1870 can be best described with a quote from *David Copperfield* (1849): “There can be no disparity in marriage like unsuitability of mind and purpose”. In the novel, a character repeats this phrase to himself multiple times, attempting to grasp its depth. Unequal marriages act as a source of misery and conflict, standing out more in his later novels. Here lies an important distinction between Austen and Dickens’s critiques: Austen prioritises love and happiness between a couple while Dickens emphasizes compatibility on multiple levels (age, stature, mentality).

### Conclusion
Our hypothesis claimed that Jane Austen and Charles Dickens criticise marriage and conventions around it in their novels during the late 18th/early 19th century. We used the frequency comparison tool with a cluster of love versus money keywords to demonstrate how Austen’s novels promote marriage for emotional rather than financial sentiments. Similarly, Dickens’s novels frequently revolve around unhappy marriages and divorce. Then, with the collocation tool, we saw that in both corpora, “mr” and “mrs” are collocated with proper nouns, i.e the names of the characters (mostly male ones). As for correlations, Austen’s novels showed strong correlations between “mr”/“mrs” and ideas of worth, feeding into the transactional representation of marriage. Yet, correlations in Dickens’s corpus were not significant to anything matrimonial. Finally, using the context tool to look closely at how both authors use and mould marriage, we were able to pinpoint a possible distinction between their approaches: while Austen focuses on love/affection in a couple, Dickens emphasizes compatibility (of age, stature, mentality etc.). With this evidence, we can assert that both authors certainly criticise marriage which is solely for financial gain in their novels using two different yet sometimes overlapping methods.

### Reflection
The main drawback for the collocations tool was that it failed to give any real answer in terms of what these links between the words which were used near each other meant. It is possible that the author just happened to use a group of words together. The same thing goes for the collocation tool, even though the significance value (p) gave us an accurate mathematical output that represented strong and weak correlations, it failed to provide any explicit meaning behind those correlations. 

A big limitation of the context tool is that it does not support the creation of word clusters which could help further uncover the insight we picked up from it. The tool also doesn’t provide any visualisation or metric for intuitive analysis. Lastly, and perhaps most importantly, this method leans more towards close reading than the distant reading required of digital humanities. Especially since the keyword we chose resulted in over 600 total contexts, it necessitated some manual labour. For this reason, it is unlikely that the context tool is an efficient primary device but it is definitely a great supplement to other tools.

